apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  namespace: default
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: Always
    name: nginx
    ports:
      - containerPort: 80
        protocol: TCP
    resources:
      requests:
        memory: "150Mi"
        cpu: "150m"
      limits:
        memory: "150Mi"
        cpu: "250m"
